spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/demo
    username: demo
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: host.docker.internal
      port: 6379
school:
  name: ABC School
  city: Hong Kong
  max-student-count: 1000

  